// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ValidationProofs {
    #[prost(uint64, tag="1")]
    pub sb_from: u64,
    #[prost(uint64, tag="2")]
    pub cd_from: u64,
    #[prost(uint64, tag="3")]
    pub eocd_from: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationResult {
    #[prost(uint64, tag="1")]
    pub request_id: u64,
    #[prost(uint32, tag="2")]
    pub request_type: u32,
    #[prost(int32, tag="3")]
    pub artifact_protocol: i32,
    #[prost(string, tag="4")]
    pub artifact_ref_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub object_address: ::prost::alloc::string::String,
    #[prost(int64, tag="6")]
    pub object_version: i64,
    #[prost(uint64, tag="7")]
    pub owner_version: u64,
    #[prost(uint32, tag="8")]
    pub track_id: u32,
    #[prost(string, tag="9")]
    pub file_hash_algorithm: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub file_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag="11")]
    pub proofs: ::core::option::Option<ValidationProofs>,
    #[prost(uint32, tag="12")]
    pub status: u32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationBlock {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(message, repeated, tag="7")]
    pub requests: ::prost::alloc::vec::Vec<ValidationResult>,
}
// @@protoc_insertion_point(module)
