metrics:
  wal_directory: '/tmp/grafana-agent-wal'
  global:
    scrape_interval: 30s
    remote_write:
      - url: ${GRAFANA_REMOTE_WRITE_URL}
        basic_auth:
          username: ${GRAFANA_REMOTE_WRITE_USER}
          password: ${GRAFANA_REMOTE_WRITE_PASSWORD}

  configs:
    - name: integrations
      scrape_configs:
        - job_name: 'postgres'
          static_configs:
            - targets: ['postgres-exporter:9187']
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: 'go_.*'
              action: drop

        - job_name: 'cadvisor'
          static_configs:
            - targets: [ 'cadvisor:8080' ]
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: 'go_.*'
              action: drop
            - source_labels: [ __name__ ]
              action: keep
              regex: >-
                container_cpu_usage_seconds_total|
                container_cpu_cfs_throttled_seconds_total|
                container_cpu_load_average_10s|
                container_memory_usage_bytes|
                container_memory_working_set_bytes|
                container_memory_failcnt|
                container_memory_failures_total|
                container_fs_usage_bytes|
                container_fs_io_time_seconds_total|
                container_network_receive_bytes_total|
                container_network_transmit_bytes_total|
                container_network_receive_errors_total|
                container_network_transmit_errors_total|
                container_processes|
                container_tasks_state|
                container_start_time_seconds

        - job_name: 'node_exporter'
          static_configs:
            - targets: ['node-exporter:9100']
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: 'go_.*'
              action: drop

        - job_name: 'api-client'
          metrics_path: /metrics
          static_configs:
            - targets: ['api-client:8080']
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: 'go_.*'
              action: drop